version: '3'
services:
 db:
  image: postgres:10.8
  volumes:
    - ./tmp/db:/var/lib/postgresql/data


 web:
   build:
     context: .
   command: rails s -p 3001 -b 0.0.0.0
   volumes:
     - .:/app
     - ./docker/database.yml:/app/config/database.yml
   ports:
     - 3001:3001
   depends_on:
     - db